spring:
  profiles:
    active:
    - dev-branch
---
spring:
  profiles: dev     #开发环境
  application: 
    name: microservicecloud-config-atguigu-dev-branch
---
spring:
  profiles: test   #测试环境
  application: 
    name: microservicecloud-config-atguigu-test-branch
#  请保存为UTF-8格式
 
 
